# Generated by Django 4.2.16 on 2026-06-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="destinations/"),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TravelPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("beach", "Beach"),
                            ("hill", "Hill Station"),
                            ("adventure", "Adventure"),
                            ("pilgrimage", "Pilgrimage"),
                            ("honeymoon", "Honeymoon"),
                            ("wildlife", "Wildlife"),
                            ("international", "International"),
                            ("city", "City Tour"),
                            ("cultural", "Cultural"),
                        ],
                        default="beach",
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("discount_percent", models.PositiveSmallIntegerField(default=0)),
                ("duration_days", models.PositiveSmallIntegerField(default=3)),
                ("duration_nights", models.PositiveSmallIntegerField(default=2)),
                ("max_persons", models.PositiveSmallIntegerField(default=10)),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
                (
                    "inclusions",
                    models.TextField(blank=True, help_text="One item per line"),
                ),
                (
                    "exclusions",
                    models.TextField(blank=True, help_text="One item per line"),
                ),
                ("itinerary", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="packages/thumbnails/"
                    ),
                ),
                (
                    "gallery_images",
                    models.TextField(
                        blank=True, help_text="Comma-separated image URLs"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "is_voucher_applicable",
                    models.BooleanField(
                        default=True,
                        help_text="Can Urban Holidays vouchers be used for this package?",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="packages.destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travel Package",
                "verbose_name_plural": "Travel Packages",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
