# Generated by Django 4.2.16 on 2026-06-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="payment_method",
            field=models.CharField(
                default="paytm_qr",
                help_text="paytm_qr / razorpay / manual",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True,
                help_text="Payment screenshot uploaded by customer",
                null=True,
                upload_to="vouchers/payment_proofs/",
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="utr_number",
            field=models.CharField(
                blank=True,
                help_text="UPI Transaction / UTR number submitted by customer",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment Verification"),
                    ("active", "Active"),
                    ("used", "Used"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
