# Generated by Django 4.2.16 on 2026-06-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vouchers", "0002_voucher_payment_method_voucher_payment_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="reward_detail",
            field=models.CharField(
                blank=True,
                help_text="Extra detail e.g. cashback amount",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="reward_revealed",
            field=models.BooleanField(
                default=False, help_text="Has the user revealed/seen their reward?"
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cashback", "💰 Cashback"),
                    ("wonderla", "🎡 Wonderla Ticket"),
                    ("gold", "🥇 Gold Gift"),
                    ("silver", "🥈 Silver Gift"),
                    ("trip", "✈️ Trip (500 Days + Free Accommodation + Activities)"),
                    ("boat_headset", "🎧 Boat Headset"),
                    ("digital_watch", "⌚ Digital Watch"),
                ],
                default="",
                help_text="Randomly assigned reward",
                max_length=30,
            ),
        ),
    ]
